seven_dof_arm:
  # Joint State Controllers

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50 # 50Hz

  # Position Controllers assigned to 7 joints and define PID gains

  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: shoulder_pan_joint
    pid: { p: 100, i: 0.01, d: 10 }

  joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: shoulder_pitch_joint
    pid: { p: 100, i: 0.01, d: 10 }

  joint3_position_controller:
    type: position_controllers/JointPositionController
    joint: elbow_roll_joint
    pid: { p: 100, i: 0.01, d: 10 }

  joint4_position_controller:
    type: position_controllers/JointPositionController
    joint: elbow_pitch_joint
    pid: { p: 100, i: 0.01, d: 10 }

  joint5_position_controller:
    type: position_controllers/JointPositionController
    joint: wrist_roll_joint
    pid: { p: 100, i: 0.01, d: 10 }

  joint6_position_controller:
    type: position_controllers/JointPositionController
    joint: wrist_pitch_joint
    pid: { p: 100, i: 0.01, d: 10 }

  joint7_position_controller:
    type: position_controllers/JointPositionController
    joint: gripper_roll_joint
    pid: { p: 100, i: 0.01, d: 10 }
